[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nickcipher"
version = "0.1.0"
description = "Emoji-based cipher tool for CLI using weighted randomly generated keys."
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Nicklas Thegerström", email = "nicklas.thegerstrom@gmail.com" }]

# Optional (only if you have deps)
# dependencies = ["rich>=13"]

[project.scripts]
nickcipher = "nickcipher.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "examples*"]